# Generated by Django 5.0.6 on 2025-05-22 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Afiliado', models.CharField(max_length=100)),
                ('direccion_Afiliados', models.CharField(max_length=180)),
                ('telefono_Afiliado', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Contacto', models.CharField(max_length=100)),
                ('email_Contacto', models.EmailField(max_length=15)),
                ('mensaje', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Especialidad', models.CharField(max_length=100)),
                ('nombre_Medico', models.CharField(max_length=100)),
                ('descripcion_especialidad', models.CharField(max_length=180)),
                ('ubicacion_Especialidad', models.CharField(max_length=180)),
                ('telefono_Especialidad', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmacias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Farmacia', models.CharField(max_length=100)),
                ('direccion_Farmacia', models.CharField(max_length=180)),
                ('telefono_Farmacia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clinicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Clinica', models.CharField(max_length=100)),
                ('direccion_Clinica', models.CharField(max_length=180)),
                ('horario', models.TimeField()),
                ('telefono_Clinica', models.CharField(max_length=100)),
                ('Provincias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clinicas', to='api.provincias')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=180)),
                ('telefono', models.CharField(max_length=100)),
                ('esta_afiliado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
