# Generated by Django 5.0.6 on 2025-05-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Afiliados',
        ),
    ]
