# Generated by Django 5.0.6 on 2025-05-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_afiliados'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('afiliado', 'Afiliado'), ('usuario', 'Usuario')], default='usuario', max_length=20),
        ),
    ]
