# Generated by Django 5.0.6 on 2025-05-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuarios_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacias',
            name='horario_Farmacia',
            field=models.TextField(default='No hay horario'),
            preserve_default=False,
        ),
    ]
