# Generated by Django 5.0.6 on 2025-06-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_farmacias_horario_farmacia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidades',
            old_name='nombre_Medico',
            new_name='nombre_Medico_Clinica',
        ),
    ]
