# Generated by Django 5.0.6 on 2025-06-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_nombre_medico_especialidades_nombre_medico_clinica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidades',
            old_name='descripcion_especialidad',
            new_name='descripcion_Especialidad',
        ),
    ]
