# Generated by Django 5.0.6 on 2025-06-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_descripcion_especialidad_especialidades_descripcion_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincias',
            name='nombre_Provincia',
            field=models.CharField(choices=[('alajuela', 'ALAJUELA'), ('heredia', 'HEREDIA'), ('cartago', 'CARTAGO'), ('san josé', 'SAN JOSÉ'), ('limón', 'LIMÓN'), ('puntarenas', 'PUNTARENAS'), ('guanacaste', 'GUANACASTE')], max_length=20),
        ),
    ]
