# Generated by Django 5.0.6 on 2025-06-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_provincias_nombre_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacias',
            name='sucursales_Farmacia',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
