# Generated by Django 5.0.6 on 2025-06-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_farmacias_director_farmacia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='esta_afiliado',
            new_name='esta_asociado',
        ),
        migrations.AddField(
            model_name='farmacias',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('asociado', 'Asociado'), ('usuario', 'Usuario')], default='usuario', max_length=20),
        ),
    ]
