# Generated by Django 5.0.6 on 2025-06-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_esta_afiliado_usuarios_esta_asociado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacias',
            name='img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
