# Generated by Django 5.0.6 on 2025-06-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_centro_remove_especialidades_nombre_medico_clinica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidades',
            name='telefono_Especialidad',
        ),
    ]
