# Generated by Django 5.0.6 on 2025-06-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_especialidades_telefono_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paquete', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=180)),
                ('precio_Paquete', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
